In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df=pd.read_csv('practiceor.csv')
df.head(10)

,id,age,education_level,company_size,job_satisfaction,experience_level,salary
0,1,28,High School,Small,Medium,Intermediate,36657
1,2,47,High School,Large,Very High,Beginner,35674
2,3,52,High School,Small,Very Low,Intermediate,33811
3,4,48,High School,Large,Low,Expert,55111
4,5,37,Master,Small,Low,Expert,81074
5,6,44,Bachelor,Small,Medium,Beginner,36519
6,7,49,High School,Medium,Medium,Advanced,43711
7,8,59,High School,Medium,Very Low,Advanced,50299
8,9,34,Master,Large,Low,Beginner,46250
9,10,37,Master,Small,Low,Beginner,51727

In [3]:
df['education_level'].value_counts()

education_level
PhD            57
High School    56
Bachelor       47
Master         40
Name: count, dtype: int64

In [4]:
df['job_satisfaction'].value_counts()

job_satisfaction
Medium       43
Low          43
High         41
Very High    40
Very Low     33
Name: count, dtype: int64

In [5]:
df['experience_level'].value_counts()

experience_level
Advanced        61
Beginner        53
Intermediate    48
Expert          38
Name: count, dtype: int64

In [6]:
df['company_size'].value_counts()

company_size
Small     71
Large     66
Medium    63
Name: count, dtype: int64

In [14]:
df.shape

(200, 7)

In [50]:
X_train,X_test,Y_train,Y_test=train_test_split( df.iloc[:,2:6],df.iloc[:,-1],test_size=0.2)
X_train

    education_level company_size job_satisfaction experience_level
199     High School        Small              Low     Intermediate
29         Bachelor       Medium        Very High           Expert
63      High School       Medium        Very High     Intermediate
165             PhD        Small             High           Expert
125          Master       Medium        Very High         Advanced
..              ...          ...              ...              ...
77      High School        Large           Medium         Advanced
140        Bachelor        Small              Low         Beginner
15      High School        Small        Very High         Advanced
175     High School       Medium              Low         Advanced
155     High School       Medium        Very High         Beginner

[160 rows x 4 columns]

In [51]:
oe=OrdinalEncoder(categories=[['High School','Bachelor','Master','PhD'],
                              ['Small','Medium','Large'],
                              ['Very Low','Low','Medium','High','Very High'],
                              ['Beginner','Intermediate','Advanced','Expert']
                              
                              ])
oe.fit(X_train)

OrdinalEncoder(categories=[['High School', 'Bachelor', 'Master', 'PhD'],
                           ['Small', 'Medium', 'Large'],
                           ['Very Low', 'Low', 'Medium', 'High', 'Very High'],
                           ['Beginner', 'Intermediate', 'Advanced', 'Expert']])

In [52]:
X_train =oe.transform(X_train)
X_test =oe.transform(X_test)

In [53]:
X_train

array([[0., 0., 1., 1.],
       [1., 1., 4., 3.],
       [0., 1., 4., 1.],
       [3., 0., 3., 3.],
       [2., 1., 4., 2.],
       [3., 1., 0., 3.],
       [2., 0., 3., 2.],
       [3., 1., 0., 1.],
       [2., 0., 4., 2.],
       [1., 1., 1., 0.],
       [0., 1., 2., 2.],
       [1., 1., 2., 1.],
       [3., 1., 3., 2.],
       [3., 0., 4., 1.],
       [0., 2., 2., 1.],
       [2., 0., 4., 2.],
       [3., 2., 4., 2.],
       [2., 1., 3., 1.],
       [3., 0., 0., 0.],
       [3., 1., 1., 1.],
       [3., 1., 2., 1.],
       [2., 2., 1., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.],
       [2., 0., 1., 2.],
       [1., 1., 0., 2.],
       [0., 1., 4., 1.],
       [3., 2., 3., 2.],
       [3., 2., 3., 2.],
       [0., 2., 3., 2.],
       [0., 1., 1., 1.],
       [3., 0., 3., 1.],
       [0., 0., 4., 1.],
       [1., 0., 3., 0.],
       [2., 0., 4., 1.],
       [3., 2., 3., 0.],
       [0., 2., 1., 0.],
       [2., 1., 3., 2.],
       [1., 2., 4., 0.],
       [2., 0., 2., 3.],
       [1., 0., 1., 3.],
       [1., 1., 2., 3.],
       [0., 1., 0., 1.],
       [1., 0., 4., 3.],
       [3., 1., 2., 3.],
       [2., 2., 4., 1.],
       [1., 1., 0., 1.],
       [0., 1., 4., 3.],
       [2., 2., 4., 1.],
       [1., 0., 0., 1.],
       [0., 2., 1., 3.],
       [3., 2., 2., 2.],
       [0., 2., 2., 1.],
       [2., 0., 4., 2.],
       [2., 2., 0., 1.],
       [3., 0., 0., 0.],
       [1., 2., 4., 2.],
       [3., 1., 0., 0.],
       [1., 2., 2., 3.],
       [3., 1., 1., 3.],
       [1., 1., 2., 2.],
       [2., 0., 2., 3.],
       [1., 0., 1., 2.],
       [0., 0., 3., 3.],
       [2., 2., 4., 0.],
       [0., 0., 0., 0.],
       [3., 2., 2., 3.],
       [3., 0., 1., 0.],
       [3., 2., 2., 3.],
       [0., 1., 2., 2.],
       [0., 0., 0., 2.],
       [3., 2., 3., 0.],
       [1., 2., 2., 3.],
       [1., 0., 4., 3.],
       [0., 2., 4., 0.],
       [0., 0., 4., 2.],
       [3., 2., 2., 0.],
       [2., 0., 3., 0.],
       [0., 1., 1., 0.],
       [3., 0., 3., 0.],
       [0., 1., 3., 1.],
       [0., 1., 2., 0.],
       [1., 0., 0., 3.],
       [1., 1., 1., 2.],
       [1., 1., 3., 1.],
       [2., 2., 3., 2.],
       [2., 0., 2., 1.],
       [2., 0., 0., 0.],
       [1., 0., 3., 3.],
       [1., 2., 2., 0.],
       [0., 0., 4., 0.],
       [2., 0., 1., 2.],
       [3., 2., 0., 0.],
       [3., 1., 1., 0.],
       [3., 2., 2., 1.],
       [3., 1., 4., 3.],
       [3., 0., 2., 2.],
       [3., 2., 3., 1.],
       [2., 0., 2., 2.],
       [0., 0., 1., 1.],
       [0., 0., 1., 2.],
       [1., 0., 0., 1.],
       [3., 1., 4., 1.],
       [2., 1., 3., 3.],
       [0., 0., 3., 2.],
       [1., 2., 1., 2.],
       [0., 2., 3., 3.],
       [0., 0., 4., 3.],
       [3., 2., 3., 1.],
       [0., 1., 4., 0.],
       [3., 1., 3., 3.],
       [2., 2., 2., 3.],
       [0., 2., 2., 0.],
       [0., 1., 0., 2.],
       [1., 1., 3., 3.],
       [2., 1., 3., 0.],
       [2., 2., 2., 0.],
       [1., 2., 1., 3.],
       [0., 1., 2., 1.],
       [3., 1., 0., 1.],
       [2., 2., 2., 2.],
       [3., 0., 1., 2.],
       [3., 2., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 2., 2.],
       [3., 0., 4., 1.],
       [0., 0., 2., 0.],
       [0., 1., 4., 0.],
       [0., 2., 3., 1.],
       [3., 2., 1., 1.],
       [2., 0., 0., 1.],
       [1., 0., 3., 2.],
       [0., 2., 3., 2.],
       [2., 0., 2., 2.],
       [0., 2., 1., 1.],
       [3., 2., 1., 0.],
       [1., 0., 2., 0.],
       [3., 0., 0., 2.],
       [0., 0., 0., 1.],
       [0., 2., 0., 2.],
       [1., 2., 3., 0.],
       [3., 2., 1., 3.],
       [2., 0., 4., 0.],
       [1., 0., 4., 0.],
       [3., 2., 4., 2.],
       [2., 1., 2., 0.],
       [3., 1., 0., 0.],
       [1., 2., 4., 0.],
       [3., 2., 2., 0.],
       [1., 2., 4., 2.],
       [3., 1., 2., 0.],
       [1., 1., 1., 0.],
       [2., 1., 3., 3.],
       [1., 1., 4., 2.],
       [0., 1., 3., 0.],
       [0., 2., 2., 2.],
       [1., 0., 1., 0.],
       [0., 0., 4., 2.],
       [0., 1., 1., 2.],
       [0., 1., 4., 0.]])